# Generated by Django 4.2.6 on 2023-10-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
